### ISSUE TITLE
Training / testing dataset 

### ISSUE THREAD

**Issue by Dylan1021** [leylabmpi/resmico#32]
Hi, 
Thanks for your great work! I want to reproduce your work for learning, could you please provide the training and testing dataset you mentioned in your paper? I really need them as I am struggling with the simulation processing. :(

**Comment by helgako** [comment]
Hi,
you can download the data from the following link http://ftp.tue.mpg.de/ebio/projects/ResMiCo/

**Comment by Dylan1021** [comment]
wow ! Thanks a lot !

**Comment by Dylan1021** [comment]
Hi,
I have downloaded the evaluation dataset n9k-novel, but there are only feature files. Could you please provide the material files? Like reference, reads, contigs. :)

**Comment by nick-youngblut** [comment]
Sorry @Dylan1021 for not responding earlier. We did not keep all of the other associated fields (e.g., reads and contigs) due to the very large total size of those files. We do provide the Snakemake pipeline for creating more data yourself. Please let me know if you have any questions about the pipeline.

**Comment by Dylan1021** [comment]
Never mind. I see, I will follow the pipeline you provided. Many thanks for your patience~
